import { Inter } from "next/font/google";
import "./globals.css";
import Navigations from "../Component/navigation/page";
import Footer from "../footer/page";

const inter = Inter({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigations />
        {children}
        <Footer />
      </body>
    </html>
  );
}
